Review
wayfair/WANDS pull request #1
Opened 2022-01-06 15:25 UTC by ecir2022

## Description

This PR is to update the WANDS project Github repository. We have done:

- updated org_name, project_name, etc in corresponding files according to README.md template.
- uploaded the data files, annotation guidelines, and notebook script in the WANDS project.

## Type of Change

- [ ] Bug Fix
- [X] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [X] I have read the [contributing guidelines](https://github.com/wayfair/WANDS/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [X] I have verified this change is not present in other open pull requests
- [X] Functionality is documented
- [X] All code style checks pass
- [X] New code contribution is covered by automated tests
- [x] All new and existing tests pass

2022-01-07 18:02 UTC, lelia requested changes
@ecir2022 Thanks for putting this together! I've suggested some URL fixes, markdown formatting enhancements as well as a few typos.

2022-01-07 19:53 UTC, ecir2022 reviewed
Thanks for the valuable comments! I have updated accordingly. Let me know if there is any issue

2022-01-10 23:39 UTC, lelia approved these changes
LGTM from my end!

2022-01-11 16:18 UTC, jdhmtl approved these changes

2022-01-18 16:29 UTC, merged